# Generated by Django 2.0.1 on 2018-10-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(default='0', max_length=50)),
                ('description', models.CharField(default='0', max_length=100)),
                ('skills', models.CharField(default='0', max_length=50)),
                ('thumbnailimage', models.CharField(default='0', max_length=50)),
                ('nDate', models.DateTimeField()),
            ],
        ),
    ]
