# Generated by Django 2.0.1 on 2018-10-11 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainx', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episodetitle', models.CharField(default='0', max_length=100)),
                ('episodedesc', models.CharField(default='0', max_length=50)),
                ('episodethumbnailimage', models.CharField(default='0', max_length=50)),
                ('episodeURL', models.CharField(default='0', max_length=50)),
                ('nDate', models.DateTimeField()),
                ('courseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainx.Courses')),
            ],
        ),
    ]
