# Generated by Django 2.0.1 on 2018-11-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainx', '0002_singlecourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('uname', models.CharField(default='0', max_length=20)),
                ('uemail', models.CharField(default='0', max_length=30)),
                ('upass', models.CharField(default='0', max_length=20)),
                ('uImg', models.CharField(default='0', max_length=50)),
                ('nDate', models.DateTimeField()),
            ],
        ),
    ]
