# Generated by Django 2.0.1 on 2018-11-27 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainx', '0004_auto_20181127_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
