# Generated by Django 2.0.1 on 2018-12-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainx', '0005_auto_20181127_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='coursecount',
            field=models.CharField(default='0', max_length=5),
        ),
    ]
