# Generated by Django 2.0.1 on 2018-12-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainx', '0006_courses_coursecount'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='difficulty',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
